name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: usecase
    attributes: {label: Problem or use case}
    validations: {required: true}
  - type: textarea
    id: proposal
    attributes: {label: Proposed solution}
    validations: {required: true}
